### ISSUE TITLE
推理场景疑问

### ISSUE THREAD

**Issue by 1qweasdzxc** [Lemonace/PIER_code#2]
请问permutation-level click behavior sequence这个序列在美团那是三个item的卡片点击序列吗？如果是，推理时候会不会存在用户点击的序列很久没点导致兴趣变化？不同于全网点击行为

**Comment by Lemonace** [comment]
permutation-level click behavior sequence是用户最近一段时间历史点击的page，和target的序列没有关系。   对于历史点击的item，我们会找到它的上下文拼成一个page，表示用户感兴趣的页面。
